-- EcoLot LK: reference data and local demonstration accounts
-- =========================================================
-- Import schema.sql first, then import this file in phpMyAdmin.
-- Existing installations: apply required database/migrations separately.
-- This file adds missing records. It does not reset the database.
-- Re-imports preserve names, passwords, account states, addresses and review history.
-- Exception: PDF-excluded items remain DO_NOT_COLLECT.
-- No campaigns, schedules, pickup requests or fabricated risk rules are created.
-- Demo logins (local development only), password: Password123
--   Admin: 0771111111 | Officer: 0772222222 | Collector: 0773333333
--   Recycler: 0774444444 | Public user: 0775555555
-- =========================================================

USE `ecolot_lk`;
SET NAMES utf8mb4;
START TRANSACTION;

-- =========================================================
-- 1. Postal code areas (existing project reference values)
-- =========================================================
INSERT INTO `postal_code_areas` (`postal_code`, `area_name`, `area_status`)
VALUES
    ('11100', 'Wellawatte', 'ACTIVE'),
    ('10800', 'Rajagiriya', 'ACTIVE'),
    ('10600', 'Narahenpita', 'ACTIVE'),
    ('10500', 'Kollupitiya', 'ACTIVE'),
    ('00800', 'Borella', 'ACTIVE'),
    ('00700', 'Cinnamon Gardens', 'ACTIVE')
ON DUPLICATE KEY UPDATE
    `postal_area_id` = `postal_area_id`;

-- =========================================================
-- 2. Waste categories
-- =========================================================
INSERT INTO `waste_categories` (`category_name`, `description`, `category_status`)
VALUES
    ('Automobile E-Waste', 'E-Waste generated by vehicle and automotive systems.', 'ACTIVE'),
    ('Domestic E-Waste', 'E-Waste generated by households.', 'ACTIVE'),
    ('Industrial E-Waste', 'E-Waste generated by industrial systems.', 'ACTIVE'),
    ('Medical E-Waste', 'Electronic waste generated by medical equipment.', 'ACTIVE'),
    ('Office E-Waste', 'E-Waste generated by offices and businesses.', 'ACTIVE'),
    ('E-Waste We Do Not Collect', 'Excluded items from the EDIC list, unavailable for pickup.', 'ACTIVE')
ON DUPLICATE KEY UPDATE
    `category_id` = `category_id`;

-- =========================================================
-- 3. Item catalogue from Ewaste.pdf (EDIC - University of Kelaniya)
-- PDF groupings retained, with consistent spaces around slashes.
-- The PDF specifies no risk levels: new items use the schema LOW default,
-- an application placeholder, not a verified safety assessment.
-- Existing item policies, risk levels and activation states are preserved.
-- PDF exclusions are enforced as DO_NOT_COLLECT and hidden from pickup options.
-- No condition-specific risk rules are inferred from the document.
-- =========================================================
-- Domestic E-Waste
INSERT INTO e_waste_items (category_id, item_name, collection_status, item_status)
SELECT c.category_id, source.item_name, 'ACCEPTED', 'ACTIVE'
FROM waste_categories c
JOIN (
    SELECT 'LCD TVs / Monitors' AS item_name
    UNION ALL SELECT 'LED lamps' AS item_name
    UNION ALL SELECT 'Computer hardware' AS item_name
    UNION ALL SELECT 'Radios, DVD players' AS item_name
    UNION ALL SELECT 'Electric ovens / Microwave ovens' AS item_name
    UNION ALL SELECT 'Fans / Hair dryers' AS item_name
    UNION ALL SELECT 'Electronic exercise equipment' AS item_name
    UNION ALL SELECT 'Mobile phones / Laptops / Chargers' AS item_name
    UNION ALL SELECT 'Bluetooth speakers / Earbuds' AS item_name
    UNION ALL SELECT 'Cameras / CCTV equipment' AS item_name
) AS source ON 1 = 1
WHERE c.category_name = 'Domestic E-Waste'
ON DUPLICATE KEY UPDATE waste_item_id = waste_item_id;

-- Office E-Waste
INSERT INTO e_waste_items (category_id, item_name, collection_status, item_status)
SELECT c.category_id, source.item_name, 'ACCEPTED', 'ACTIVE'
FROM waste_categories c
JOIN (
    SELECT 'Photocopy machines' AS item_name
    UNION ALL SELECT 'UPS units / UPS batteries' AS item_name
    UNION ALL SELECT 'Printers / Scanners' AS item_name
    UNION ALL SELECT 'Projectors / Speakers' AS item_name
    UNION ALL SELECT 'Access control equipment (fingerprint machines)' AS item_name
    UNION ALL SELECT 'Network equipment' AS item_name
    UNION ALL SELECT 'Telephone / Fax / Intercom equipment' AS item_name
    UNION ALL SELECT 'Barcode readers / POS machines' AS item_name
) AS source ON 1 = 1
WHERE c.category_name = 'Office E-Waste'
ON DUPLICATE KEY UPDATE waste_item_id = waste_item_id;

-- Automobile E-Waste
INSERT INTO e_waste_items (category_id, item_name, collection_status, item_status)
SELECT c.category_id, source.item_name, 'ACCEPTED', 'ACTIVE'
FROM waste_categories c
JOIN (
    SELECT 'Dashboard electronics' AS item_name
    UNION ALL SELECT 'LED headlights' AS item_name
    UNION ALL SELECT 'Hybrid batteries / EV batteries' AS item_name
    UNION ALL SELECT 'Motors / Alternators' AS item_name
    UNION ALL SELECT 'Switches' AS item_name
    UNION ALL SELECT 'Sensors' AS item_name
    UNION ALL SELECT 'Cables' AS item_name
    UNION ALL SELECT 'Relays' AS item_name
    UNION ALL SELECT 'Heaters' AS item_name
) AS source ON 1 = 1
WHERE c.category_name = 'Automobile E-Waste'
ON DUPLICATE KEY UPDATE waste_item_id = waste_item_id;

-- Industrial E-Waste
INSERT INTO e_waste_items (category_id, item_name, collection_status, item_status)
SELECT c.category_id, source.item_name, 'ACCEPTED', 'ACTIVE'
FROM waste_categories c
JOIN (
    SELECT 'Inverters / VFDs' AS item_name
    UNION ALL SELECT 'CNC machines' AS item_name
    UNION ALL SELECT 'Elevator electronic components' AS item_name
    UNION ALL SELECT 'Sign board displays' AS item_name
    UNION ALL SELECT 'Air conditioners' AS item_name
    UNION ALL SELECT 'Automation equipment' AS item_name
    UNION ALL SELECT 'Power supply units' AS item_name
    UNION ALL SELECT 'Vending machine hardware' AS item_name
    UNION ALL SELECT 'Solar power equipment' AS item_name
) AS source ON 1 = 1
WHERE c.category_name = 'Industrial E-Waste'
ON DUPLICATE KEY UPDATE waste_item_id = waste_item_id;

-- Medical E-Waste
INSERT INTO e_waste_items (category_id, item_name, collection_status, item_status)
SELECT c.category_id, source.item_name, 'ACCEPTED', 'ACTIVE'
FROM waste_categories c
JOIN (
    SELECT 'Ventilators / Insulin pumps' AS item_name
    UNION ALL SELECT 'Hearing aids / Electric wheelchairs' AS item_name
    UNION ALL SELECT 'Oximeters / Electronic thermometers' AS item_name
    UNION ALL SELECT 'Ultrasound machines and probes' AS item_name
    UNION ALL SELECT 'Centrifuges / Spectrophotometers' AS item_name
    UNION ALL SELECT 'Electronic medical record systems' AS item_name
    UNION ALL SELECT 'Glucometers / Weight scales' AS item_name
) AS source ON 1 = 1
WHERE c.category_name = 'Medical E-Waste'
ON DUPLICATE KEY UPDATE waste_item_id = waste_item_id;

-- E-Waste We Do Not Collect
INSERT INTO e_waste_items (category_id, item_name, collection_status, item_status)
SELECT c.category_id, source.item_name, 'DO_NOT_COLLECT', 'ACTIVE'
FROM waste_categories c
JOIN (
    SELECT 'CFL bulbs / Tube lights / Mercury lamps' AS item_name
    UNION ALL SELECT 'Refrigerators / Washing machines' AS item_name
    UNION ALL SELECT 'CRT TVs / CRT monitors' AS item_name
    UNION ALL SELECT 'Leaking batteries' AS item_name
    UNION ALL SELECT 'CT scanners / X-ray equipment' AS item_name
    UNION ALL SELECT 'Smoke detectors / Radioactive sources' AS item_name
    UNION ALL SELECT 'Items containing mercury, cadmium, phosphorous' AS item_name
    UNION ALL SELECT 'Biohazardous equipment' AS item_name
) AS source ON 1 = 1
WHERE c.category_name = 'E-Waste We Do Not Collect'
ON DUPLICATE KEY UPDATE collection_status = 'DO_NOT_COLLECT';

-- End PDF e-waste catalogue

-- =========================================================
-- 4. Local demo users and role profiles
-- Password hashes are used only when inserting a new account.
-- =========================================================

-- 1. Admin
INSERT INTO `users` (
    `full_name`, `mobile_number`, `email`, `password_hash`, `role`, `account_status`, `mobile_verified_at`
) VALUES (
    'System Administrator', '94771111111', 'admin@ecolot.lk',
    '$2y$12$AAef065V6ONGJxu69dJv1O9CkiN49RCVBXJiDiCuMAZwJDxXsXKei',
    'ADMIN', 'ACTIVE', NOW()
) ON DUPLICATE KEY UPDATE `user_id` = `user_id`;

SET @admin_id = (SELECT `user_id` FROM `users` WHERE `mobile_number` = '94771111111' AND `role` = 'ADMIN');

INSERT INTO `administrators` (`user_id`)
SELECT @admin_id WHERE @admin_id IS NOT NULL
ON DUPLICATE KEY UPDATE `user_id` = VALUES(`user_id`);

-- 2. Municipal Officer
INSERT INTO `users` (
    `full_name`, `mobile_number`, `email`, `password_hash`, `role`, `account_status`, `mobile_verified_at`
) VALUES (
    'Municipal Officer', '94772222222', 'officer@ecolot.lk',
    '$2y$12$AAef065V6ONGJxu69dJv1O9CkiN49RCVBXJiDiCuMAZwJDxXsXKei',
    'MUNICIPAL_OFFICER', 'ACTIVE', NOW()
) ON DUPLICATE KEY UPDATE `user_id` = `user_id`;

SET @officer_id = (SELECT `user_id` FROM `users` WHERE `mobile_number` = '94772222222' AND `role` = 'MUNICIPAL_OFFICER');

INSERT INTO `municipal_officers` (`user_id`)
SELECT @officer_id WHERE @officer_id IS NOT NULL
ON DUPLICATE KEY UPDATE `user_id` = VALUES(`user_id`);

-- October 2026 demo campaign for Area Collection Schedule CRUD
-- Re-importing ensures this demo campaign is available and OPEN.
INSERT INTO `monthly_campaigns` (
    `created_by_officer_user_id`, `campaign_name`, `campaign_month`, `campaign_status`
)
SELECT
    @officer_id, 'October 2026 E-Waste Collection Campaign', '2026-10-01', 'OPEN'
WHERE @officer_id IS NOT NULL
ON DUPLICATE KEY UPDATE
    `campaign_name` = VALUES(`campaign_name`),
    `campaign_status` = 'OPEN';

-- 3. Collector
INSERT INTO `users` (
    `full_name`, `mobile_number`, `email`, `password_hash`, `role`, `account_status`, `mobile_verified_at`
) VALUES (
    'Eco Collector', '94773333333', 'collector@ecolot.lk',
    '$2y$12$AAef065V6ONGJxu69dJv1O9CkiN49RCVBXJiDiCuMAZwJDxXsXKei',
    'COLLECTOR', 'ACTIVE', NOW()
) ON DUPLICATE KEY UPDATE `user_id` = `user_id`;

SET @collector_id = (SELECT `user_id` FROM `users` WHERE `mobile_number` = '94773333333' AND `role` = 'COLLECTOR');

INSERT INTO `collectors` (`user_id`)
SELECT @collector_id WHERE @collector_id IS NOT NULL
ON DUPLICATE KEY UPDATE `user_id` = VALUES(`user_id`);

-- 4. Authorized Recycler
INSERT INTO `users` (
    `full_name`, `mobile_number`, `email`, `password_hash`, `role`, `account_status`, `mobile_verified_at`
) VALUES (
    'Green Recyclers Ltd', '94774444444', 'recycler@ecolot.lk',
    '$2y$12$AAef065V6ONGJxu69dJv1O9CkiN49RCVBXJiDiCuMAZwJDxXsXKei',
    'RECYCLER', 'ACTIVE', NOW()
) ON DUPLICATE KEY UPDATE `user_id` = `user_id`;

SET @recycler_id = (SELECT `user_id` FROM `users` WHERE `mobile_number` = '94774444444' AND `role` = 'RECYCLER');

-- Older installations use verified_*; current schema uses reviewed_*.
-- Select the matching audit columns without altering existing tables/data.
SET @recycler_uses_reviewed = EXISTS (
    SELECT 1 FROM information_schema.COLUMNS
    WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'authorized_recyclers'
      AND COLUMN_NAME = 'reviewed_by_admin_user_id'
);
SET @recycler_reviewer_column = IF(@recycler_uses_reviewed,
    'reviewed_by_admin_user_id', 'verified_by_admin_user_id');
SET @recycler_review_date_column = IF(@recycler_uses_reviewed,
    'reviewed_at', 'verified_at');
SET @recycler_seed_sql = CONCAT(
    'INSERT INTO authorized_recyclers (user_id, company_name, business_address, district, verification_status, `',
    @recycler_reviewer_column, '`, `', @recycler_review_date_column,
    '`) SELECT ?, ''Green Recyclers Pvt Ltd'', ''45 Industrial Zone, Colombo'', ''Colombo'', ''VERIFIED'', ?, NOW() WHERE @recycler_id IS NOT NULL AND @admin_id IS NOT NULL ',
    'ON DUPLICATE KEY UPDATE user_id = authorized_recyclers.user_id'
);
-- Preserve the status and audit history of an existing recycler on repeat imports.
PREPARE recycler_seed_statement FROM @recycler_seed_sql;
EXECUTE recycler_seed_statement USING @recycler_id, @admin_id;
DEALLOCATE PREPARE recycler_seed_statement;

-- 5. Public User
INSERT INTO `users` (
    `full_name`, `mobile_number`, `email`, `password_hash`, `role`, `account_status`, `mobile_verified_at`
) VALUES (
    'Public Resident', '94775555555', 'user@ecolot.lk',
    '$2y$12$AAef065V6ONGJxu69dJv1O9CkiN49RCVBXJiDiCuMAZwJDxXsXKei',
    'PUBLIC_USER', 'ACTIVE', NOW()
) ON DUPLICATE KEY UPDATE `user_id` = `user_id`;

SET @public_user_id = (SELECT `user_id` FROM `users` WHERE `mobile_number` = '94775555555' AND `role` = 'PUBLIC_USER');

SET @area_id = (SELECT `postal_area_id` FROM `postal_code_areas` WHERE `postal_code` = '11100' LIMIT 1);

INSERT INTO `public_profiles` (`user_id`, `postal_area_id`, `address`)
SELECT @public_user_id, @area_id, '123 Main Street, Wellawatte'
WHERE @public_user_id IS NOT NULL AND @area_id IS NOT NULL
ON DUPLICATE KEY UPDATE `user_id` = `user_id`;

-- 5. Finish. Re-importing is safe and does not clear operational records.
COMMIT;
