USE `ecolot_lk`;

INSERT INTO `postal_code_areas` (`postal_code`, `area_name`, `area_status`)
VALUES
    ('11100', 'Wellawatte', 'ACTIVE'),
    ('10800', 'Rajagiriya', 'ACTIVE'),
    ('10600', 'Narahenpita', 'ACTIVE'),
    ('10500', 'Kollupitiya', 'ACTIVE'),
    ('00800', 'Borella', 'ACTIVE'),
    ('00700', 'Cinnamon Gardens', 'ACTIVE')
ON DUPLICATE KEY UPDATE
    `area_name` = VALUES(`area_name`),
    `area_status` = VALUES(`area_status`);

INSERT INTO `waste_categories` (`category_name`, `description`, `category_status`)
VALUES
    ('Automobile E-Waste', 'E-Waste generated by vehicle and automotive systems.', 'ACTIVE'),
    ('Domestic E-Waste', 'E-Waste generated by households.', 'ACTIVE'),
    ('Industrial E-Waste', 'E-Waste generated by industrial systems.', 'ACTIVE'),
    ('Medical E-Waste', 'Electronic waste generated by medical equipment.', 'ACTIVE'),
    ('Office E-Waste', 'E-Waste generated by offices and businesses.', 'ACTIVE')
ON DUPLICATE KEY UPDATE
    `description` = VALUES(`description`),
    `category_status` = VALUES(`category_status`);
