USE `ecolot_lk`;

-- =========================================================
-- Seed postal code areas
-- =========================================================
INSERT INTO `postal_code_areas` (`postal_code`, `area_name`, `area_status`)
VALUES
    ('11100', 'Wellawatte', 'ACTIVE'),
    ('10800', 'Rajagiriya', 'ACTIVE'),
    ('10600', 'Narahenpita', 'ACTIVE'),
    ('10500', 'Kollupitiya', 'ACTIVE'),
    ('00800', 'Borella', 'ACTIVE'),
    ('00700', 'Cinnamon Gardens', 'ACTIVE')
ON DUPLICATE KEY UPDATE
    `area_name` = VALUES(`area_name`),
    `area_status` = VALUES(`area_status`);

-- =========================================================
-- Seed waste categories
-- =========================================================
INSERT INTO `waste_categories` (`category_name`, `description`, `category_status`)
VALUES
    ('Automobile E-Waste', 'E-Waste generated by vehicle and automotive systems.', 'ACTIVE'),
    ('Domestic E-Waste', 'E-Waste generated by households.', 'ACTIVE'),
    ('Industrial E-Waste', 'E-Waste generated by industrial systems.', 'ACTIVE'),
    ('Medical E-Waste', 'Electronic waste generated by medical equipment.', 'ACTIVE'),
    ('Office E-Waste', 'E-Waste generated by offices and businesses.', 'ACTIVE')
ON DUPLICATE KEY UPDATE
    `description` = VALUES(`description`),
    `category_status` = VALUES(`category_status`);

-- =========================================================
-- Demo Accounts Seed (Password for all accounts: Password123)
-- Hash: $2y$12$AAef065V6ONGJxu69dJv1O9CkiN49RCVBXJiDiCuMAZwJDxXsXKei
-- =========================================================

-- 1. Admin
INSERT INTO `users` (
    `full_name`, `mobile_number`, `email`, `password_hash`, `role`, `account_status`, `mobile_verified_at`
) VALUES (
    'System Administrator', '94771111111', 'admin@ecolot.lk',
    '$2y$12$AAef065V6ONGJxu69dJv1O9CkiN49RCVBXJiDiCuMAZwJDxXsXKei',
    'ADMIN', 'ACTIVE', NOW()
) ON DUPLICATE KEY UPDATE `account_status` = 'ACTIVE';

SET @admin_id = (SELECT `user_id` FROM `users` WHERE `mobile_number` = '94771111111');

INSERT INTO `administrators` (`user_id`)
VALUES (@admin_id)
ON DUPLICATE KEY UPDATE `user_id` = VALUES(`user_id`);

-- 2. Municipal Officer
INSERT INTO `users` (
    `full_name`, `mobile_number`, `email`, `password_hash`, `role`, `account_status`, `mobile_verified_at`
) VALUES (
    'Municipal Officer', '94772222222', 'officer@ecolot.lk',
    '$2y$12$AAef065V6ONGJxu69dJv1O9CkiN49RCVBXJiDiCuMAZwJDxXsXKei',
    'MUNICIPAL_OFFICER', 'ACTIVE', NOW()
) ON DUPLICATE KEY UPDATE `account_status` = 'ACTIVE';

SET @officer_id = (SELECT `user_id` FROM `users` WHERE `mobile_number` = '94772222222');

INSERT INTO `municipal_officers` (`user_id`)
VALUES (@officer_id)
ON DUPLICATE KEY UPDATE `user_id` = VALUES(`user_id`);

-- 3. Collector
INSERT INTO `users` (
    `full_name`, `mobile_number`, `email`, `password_hash`, `role`, `account_status`, `mobile_verified_at`
) VALUES (
    'Eco Collector', '94773333333', 'collector@ecolot.lk',
    '$2y$12$AAef065V6ONGJxu69dJv1O9CkiN49RCVBXJiDiCuMAZwJDxXsXKei',
    'COLLECTOR', 'ACTIVE', NOW()
) ON DUPLICATE KEY UPDATE `account_status` = 'ACTIVE';

SET @collector_id = (SELECT `user_id` FROM `users` WHERE `mobile_number` = '94773333333');

INSERT INTO `collectors` (`user_id`)
VALUES (@collector_id)
ON DUPLICATE KEY UPDATE `user_id` = VALUES(`user_id`);

-- 4. Authorized Recycler
INSERT INTO `users` (
    `full_name`, `mobile_number`, `email`, `password_hash`, `role`, `account_status`, `mobile_verified_at`
) VALUES (
    'Green Recyclers Ltd', '94774444444', 'recycler@ecolot.lk',
    '$2y$12$AAef065V6ONGJxu69dJv1O9CkiN49RCVBXJiDiCuMAZwJDxXsXKei',
    'RECYCLER', 'ACTIVE', NOW()
) ON DUPLICATE KEY UPDATE `account_status` = 'ACTIVE';

SET @recycler_id = (SELECT `user_id` FROM `users` WHERE `mobile_number` = '94774444444');

INSERT INTO `authorized_recyclers` (
    `user_id`, `company_name`, `business_address`, `district`, `verification_status`, `verified_by_admin_user_id`, `verified_at`
) VALUES (
    @recycler_id, 'Green Recyclers Pvt Ltd', '45 Industrial Zone, Colombo', 'Colombo', 'VERIFIED', @admin_id, NOW()
) ON DUPLICATE KEY UPDATE `verification_status` = 'VERIFIED';

-- 5. Public User
INSERT INTO `users` (
    `full_name`, `mobile_number`, `email`, `password_hash`, `role`, `account_status`, `mobile_verified_at`
) VALUES (
    'Public Resident', '94775555555', 'user@ecolot.lk',
    '$2y$12$AAef065V6ONGJxu69dJv1O9CkiN49RCVBXJiDiCuMAZwJDxXsXKei',
    'PUBLIC_USER', 'ACTIVE', NOW()
) ON DUPLICATE KEY UPDATE `account_status` = 'ACTIVE';

SET @public_user_id = (SELECT `user_id` FROM `users` WHERE `mobile_number` = '94775555555');

SET @area_id = (SELECT `postal_area_id` FROM `postal_code_areas` WHERE `postal_code` = '11100' LIMIT 1);

INSERT INTO `public_profiles` (`user_id`, `postal_area_id`, `address`)
VALUES (@public_user_id, @area_id, '123 Main Street, Wellawatte')
ON DUPLICATE KEY UPDATE `address` = VALUES(`address`);
