<?php
$records = [
 'DEMO-FIX-LOT-AWARDED-001'=>['category'=>'Demo Consumer Electronics','qty'=>9,'weight'=>'118.00 kg','amount'=>'132,000.00','status'=>'AWARDED','handover'=>'PENDING'],
 'DEMO-FIX-LOT-HANDED-OVER-001'=>['category'=>'Office E-Waste','qty'=>10,'weight'=>'76.00 kg','amount'=>'74,500.00','status'=>'AWARDED','handover'=>'COMPLETED'],
 'DEMO-FIX-LOT-PROCESSING-001'=>['category'=>'Demo Battery and Circuit Boards','qty'=>16,'weight'=>'64.00 kg','amount'=>'88,000.00','status'=>'PROCESSING','handover'=>'COMPLETED'],
 'DEMO-FIX-LOT-COMPLETED-001'=>['category'=>'Demo Consumer Electronics','qty'=>24,'weight'=>'18.00 kg','amount'=>'29,500.00','status'=>'COMPLETED','handover'=>'COMPLETED'],
 'DEMO-LOT-003'=>['category'=>'Demo Consumer Electronics','qty'=>8,'weight'=>'110.00 kg','amount'=>'126,000.00','status'=>'AWARDED','handover'=>'PENDING'],
 'DEMO-LOT-004'=>['category'=>'Demo Battery and Circuit Boards','qty'=>18,'weight'=>'62.00 kg','amount'=>'99,000.00','status'=>'PROCESSING','handover'=>'COMPLETED'],
];
$lotCode=(string)$eLotId; $lot=$records[$lotCode]??null;
?>
<section class="workflow-page">
<?php if ($lot===null): ?><div class="workflow-header"><div><h1>Awarded E-Lot not found</h1><p>No awarded E-Lot matches the requested code.</p></div><a class="secondary-workflow-btn" href="<?= htmlspecialchars($basePath) ?>/recycler/awarded-e-lots">Back to Awarded E-Lots</a></div>
<?php else: $status=$lot['status']; $handed=$lot['handover']==='COMPLETED'; $processing=$status==='PROCESSING'; $completed=$status==='COMPLETED'; $stage=$status==='AWARDED'?($handed?'HANDED_OVER':'AWAITING_HANDOVER'):$status; $badge=$completed?'badge-completed':($processing?'badge-processing':($handed?'badge-handed-over':'badge-awarded')); ?>
<div class="workflow-header"><div><h1>Awarded E-Lot Details</h1><p>Review award, handover and recycling progress for this E-Lot.</p></div><a class="secondary-workflow-btn" href="<?= htmlspecialchars($basePath) ?>/recycler/awarded-e-lots">Back to Awarded E-Lots</a></div><p class="page-notice" data-page-notice tabindex="-1" hidden></p>
<section class="workflow-card"><div class="workflow-section-header"><h2>Lot Information</h2></div><div class="detail-grid"><div class="detail-item"><span class="detail-label">Lot Code</span><strong><?= htmlspecialchars($lotCode) ?></strong></div><div class="detail-item"><span class="detail-label">Category</span><strong><?= htmlspecialchars($lot['category']) ?></strong></div><div class="detail-item"><span class="detail-label">Current Status</span><span class="badge <?= $badge ?>"><?= ucwords(strtolower(str_replace('_',' ',$stage))) ?></span></div><div class="detail-item"><span class="detail-label">Quantity / Weight</span><strong><?= $lot['qty'] ?> items / <?= $lot['weight'] ?></strong></div><div class="detail-item"><span class="detail-label">Winning Bid</span><strong>Rs. <?= $lot['amount'] ?></strong></div><div class="detail-item"><span class="detail-label">Award Date</span><strong>2026-07-10</strong></div></div></section>
<section class="workflow-card"><div class="workflow-section-header"><h2>Lifecycle</h2></div><div class="lifecycle" aria-label="Awarded E-Lot lifecycle"><div class="lifecycle-step complete">1. Awarded</div><div class="lifecycle-step <?= $handed?'complete':'current' ?>">2. Handed Over</div><div class="lifecycle-step <?= $completed?'complete':($processing?'current':'') ?>">3. Processing</div><div class="lifecycle-step <?= $completed?'current':'' ?>">4. Completed</div></div></section>
<section class="workflow-card"><div class="workflow-section-header"><h2>Handover</h2><p>Physical handover is recorded and confirmed by the Municipal Officer.</p></div><div class="detail-grid"><div class="detail-item"><span class="detail-label">Handover Status</span><strong><?= $handed?'Completed':'Pending Municipal Officer confirmation' ?></strong></div><div class="detail-item"><span class="detail-label">Handover Date</span><strong><?= $handed?'2026-07-12':'Not recorded' ?></strong></div><div class="detail-item"><span class="detail-label">Remarks</span><strong><?= $handed?'Physical handover recorded by Municipal Officer.':'No remarks recorded' ?></strong></div></div></section>
<section class="workflow-card"><div class="workflow-section-header"><h2>Processing</h2></div><div class="detail-grid"><div class="detail-item"><span class="detail-label">Processing Status</span><strong><?= $completed?'Completed':($processing?'In Progress':($handed?'Ready to Start':'Not Started')) ?></strong></div><div class="detail-item"><span class="detail-label">Started At</span><strong><?= ($processing||$completed)?'2026-07-13 09:00':'Not started' ?></strong></div><div class="detail-item"><span class="detail-label">Completed At</span><strong><?= $completed?'2026-07-15 16:30':'Not completed' ?></strong></div></div><?php if($status==='AWARDED' && $handed): ?><div class="form-actions"><button class="primary-workflow-btn" type="button" data-recycler-dialog="start-processing" data-elot-code="<?= htmlspecialchars($lotCode) ?>">Start Processing</button></div><?php elseif($processing): ?><div class="form-actions"><button class="primary-workflow-btn" type="button" data-recycler-dialog="complete-processing" data-elot-code="<?= htmlspecialchars($lotCode) ?>">Mark Completed</button></div><?php endif; ?></section>
<?php endif; ?></section>
