<?php
$lots = [
 ['code'=>'DEMO-LOT-002','title'=>'Demo Open Lot - Phones and Routers','council'=>'Demo Colombo Metro Council','category'=>'Demo Consumer Electronics','quantity'=>45,'weight'=>'18.00 kg','deadline'=>'2026-08-20 15:37','bid'=>'SUBMITTED','myBid'=>48200,'highestBid'=>51000,'totalBids'=>4,'bidPosition'=>'OUTBID','submitted'=>'2026-08-08'],
 ['code'=>'DEMO-FIX-LOT-OPEN-002','title'=>'Open Lot - Mobile Phones and Routers','council'=>'Colombo Metro Council','category'=>'Demo Consumer Electronics','quantity'=>50,'weight'=>'26.00 kg','deadline'=>'2026-08-22 16:03','bid'=>'SUBMITTED','myBid'=>38200,'highestBid'=>38200,'totalBids'=>3,'bidPosition'=>'LEADING','submitted'=>'2026-08-09'],
 ['code'=>'DEMO-LOT-001','title'=>'Demo Open Lot - Laptops from Nugegoda','council'=>'Demo Colombo Metro Council','category'=>'Demo Consumer Electronics','quantity'=>14,'weight'=>'91.00 kg','deadline'=>'2026-08-24 15:37','bid'=>'NONE','myBid'=>null,'highestBid'=>85000,'totalBids'=>4,'bidPosition'=>null,'submitted'=>''],
 ['code'=>'DEMO-FIX-LOT-OPEN-001','title'=>'Open Lot - Laptops and Monitors','council'=>'Colombo Metro Council','category'=>'Office E-Waste','quantity'=>12,'weight'=>'84.00 kg','deadline'=>'2026-08-25 16:03','bid'=>'SUBMITTED','myBid'=>94500,'highestBid'=>94500,'totalBids'=>5,'bidPosition'=>'LEADING','submitted'=>'2026-08-09'],
];
?>
<section class="eligible-bid-page"><section class="bid-card">
 <div class="bid-header"><div><h1>Eligible Open E-Lots</h1><p>Review E-Lots that match your approved handling capabilities.</p></div></div>
 <form class="light-filter" data-client-filter data-rows="[data-eligible-row]" data-empty="[data-eligible-filter-empty]" data-result="[data-eligible-result]"><div class="quick-filters" role="group" aria-label="Filter by my bid status"><button class="quick-filter" type="button" aria-pressed="true" data-filter-name="bid" data-filter-value="">All</button><button class="quick-filter" type="button" aria-pressed="false" data-filter-name="bid" data-filter-value="NONE">Not Bid Yet</button><button class="quick-filter" type="button" aria-pressed="false" data-filter-name="bid" data-filter-value="SUBMITTED">Bid Submitted</button></div><div class="light-filter-controls"><div class="filter-field"><label for="eligible-search">Search E-Lots</label><input id="eligible-search" name="search" type="search" placeholder="Lot code, title or category"></div><div class="filter-field"><label for="eligible-category">Category</label><select id="eligible-category" name="category"><option value="">All Categories</option><option>Demo Consumer Electronics</option><option>Office E-Waste</option></select></div></div></form>
 <p class="filter-result" data-eligible-result role="status" aria-live="polite"></p>
 <?php if ($lots === []): ?><div class="empty-state">No eligible E-Lots are available.</div><?php else: ?>
 <div class="bid-table-wrapper"><table class="bid-table"><thead><tr><th>E-Lot</th><th>Category</th><th>Waste Summary</th><th>Bidding Deadline</th><th>My Bid</th><th>Actions</th></tr></thead><tbody>
 <?php foreach ($lots as $lot): ?><tr data-eligible-row data-search="<?= htmlspecialchars($lot['code'].' '.$lot['title'].' '.$lot['category']) ?>" data-category="<?= htmlspecialchars($lot['category']) ?>" data-bid="<?= $lot['bid'] ?>">
  <td data-label="E-Lot"><strong class="table-primary-text"><?= htmlspecialchars($lot['code']) ?></strong><span class="table-secondary-text"><?= htmlspecialchars($lot['title']) ?></span></td>
  <td data-label="Category"><?= htmlspecialchars($lot['category']) ?></td>
  <td data-label="Waste Summary"><strong><?= $lot['quantity'] ?> items</strong><span class="table-secondary-text"><?= htmlspecialchars($lot['weight']) ?></span></td>
  <td data-label="Bidding Deadline"><time datetime="<?= htmlspecialchars(str_replace(' ','T',$lot['deadline'])) ?>"><?= htmlspecialchars($lot['deadline']) ?></time></td>
  <td data-label="My Bid"><div class="bid-cell"><?php if ($lot['bid']==='SUBMITTED'): ?><span><span class="status submitted">Submitted</span><span class="bid-amount-inline"> · Rs. <?= number_format($lot['myBid']) ?></span></span><?php else: ?><span class="no-bid-text">Not Bid Yet</span><?php endif; ?><span class="bid-context"><?= $lot['highestBid'] === null ? 'No bids yet' : 'Highest: Rs. '.number_format($lot['highestBid']) ?></span><?php if ($lot['bidPosition'] !== null): ?><span class="bid-position <?= strtolower($lot['bidPosition']) ?>"><?= ucfirst(strtolower($lot['bidPosition'])) ?></span><?php endif; ?></div></td>
  <td data-label="Actions"><div class="row-actions"><a class="edit-btn secondary-row-action" href="<?= htmlspecialchars($basePath) ?>/recycler/e-lot/<?= rawurlencode($lot['code']) ?>">View Details</a><?php if ($lot['bid']==='SUBMITTED'): ?><button class="edit-btn primary-row-action" type="button" data-recycler-dialog="view-bid" data-elot-code="<?= htmlspecialchars($lot['code']) ?>" data-title="<?= htmlspecialchars($lot['title']) ?>" data-category="<?= htmlspecialchars($lot['category']) ?>" data-bid-amount="<?= $lot['myBid'] ?>" data-highest-bid="<?= $lot['highestBid'] ?>" data-total-bids="<?= $lot['totalBids'] ?>" data-bid-position="<?= htmlspecialchars($lot['bidPosition']) ?>" data-bid-status="Submitted" data-submitted="<?= htmlspecialchars($lot['submitted']) ?>" data-deadline="<?= htmlspecialchars($lot['deadline']) ?>">View Bid</button><?php else: ?><button class="edit-btn primary-row-action" type="button" data-recycler-dialog="place-bid" data-elot-code="<?= htmlspecialchars($lot['code']) ?>" data-highest-bid="<?= $lot['highestBid'] ?>" data-total-bids="<?= $lot['totalBids'] ?>">Place Bid</button><?php endif; ?></div></td>
 </tr><?php endforeach; ?></tbody></table></div><div class="filtered-empty-state" data-eligible-filter-empty hidden>No E-Lots match the selected filters.</div><?php endif; ?>
</section></section>
