<?php
$lots = [
 ['code'=>'DEMO-LOT-002','title'=>'Demo Open Lot - Phones and Routers','council'=>'Demo Colombo Metro Council','category'=>'Demo Consumer Electronics','quantity'=>45,'weight'=>'18.00 kg','deadline'=>'2026-08-20 15:37','bid'=>'SUBMITTED','amount'=>'48,200.00'],
 ['code'=>'DEMO-FIX-LOT-OPEN-002','title'=>'Open Lot - Mobile Phones and Routers','council'=>'Colombo Metro Council','category'=>'Demo Consumer Electronics','quantity'=>50,'weight'=>'26.00 kg','deadline'=>'2026-08-22 16:03','bid'=>'SUBMITTED','amount'=>'38,200.00'],
 ['code'=>'DEMO-LOT-001','title'=>'Demo Open Lot - Laptops from Nugegoda','council'=>'Demo Colombo Metro Council','category'=>'Demo Consumer Electronics','quantity'=>14,'weight'=>'91.00 kg','deadline'=>'2026-08-24 15:37','bid'=>'NONE','amount'=>''],
 ['code'=>'DEMO-FIX-LOT-OPEN-001','title'=>'Open Lot - Laptops and Monitors','council'=>'Colombo Metro Council','category'=>'Office E-Waste','quantity'=>12,'weight'=>'84.00 kg','deadline'=>'2026-08-25 16:03','bid'=>'SUBMITTED','amount'=>'94,500.00'],
];
?>
<section class="eligible-bid-page"><section class="bid-card">
 <div class="bid-header"><div><h2>Eligible Open E-Lots</h2><p>Review E-Lots that match your approved handling capabilities.</p></div></div>
 <form class="light-filter" data-client-filter data-rows="[data-eligible-row]" data-empty="[data-eligible-empty]" data-result="[data-eligible-result]"><div class="quick-filters" role="group" aria-label="Filter by my bid status"><button class="quick-filter" type="button" aria-pressed="true" data-filter-name="bid" data-filter-value="">All</button><button class="quick-filter" type="button" aria-pressed="false" data-filter-name="bid" data-filter-value="NONE">Not Bid Yet</button><button class="quick-filter" type="button" aria-pressed="false" data-filter-name="bid" data-filter-value="SUBMITTED">Bid Submitted</button></div><div class="light-filter-controls"><div class="filter-field"><label for="eligible-search">Search E-Lots</label><input id="eligible-search" name="search" type="search" placeholder="Lot code or category"></div><div class="filter-field"><label for="eligible-category">Category</label><select id="eligible-category" name="category"><option value="">All Categories</option><option>Demo Consumer Electronics</option><option>Office E-Waste</option></select></div></div></form>
 <p class="filter-result" data-eligible-result role="status" aria-live="polite"></p>
 <div class="bid-table-wrapper"><table class="bid-table"><thead><tr><th>Lot Code</th><th>Title</th><th>Council</th><th>Category</th><th>Quantity</th><th>Weight</th><th>Deadline</th><th>My Bid Status</th><th>Action</th></tr></thead><tbody>
 <?php foreach ($lots as $lot): ?><tr data-eligible-row data-search="<?= htmlspecialchars($lot['code'].' '.$lot['category']) ?>" data-category="<?= htmlspecialchars($lot['category']) ?>" data-bid="<?= $lot['bid'] ?>">
  <td data-label="Lot Code"><?= htmlspecialchars($lot['code']) ?></td><td data-label="Title"><?= htmlspecialchars($lot['title']) ?></td><td data-label="Council"><?= htmlspecialchars($lot['council']) ?></td><td data-label="Category"><?= htmlspecialchars($lot['category']) ?></td><td data-label="Quantity"><?= $lot['quantity'] ?></td><td data-label="Weight"><?= htmlspecialchars($lot['weight']) ?></td><td data-label="Deadline"><?= htmlspecialchars($lot['deadline']) ?></td><td data-label="Bid Status"><?php if ($lot['bid']==='SUBMITTED'): ?><span class="status submitted">Submitted</span><span class="bid-amount">Rs. <?= $lot['amount'] ?></span><?php else: ?>Not Bid Yet<?php endif; ?></td><td data-label="Action"><div class="row-actions"><a class="edit-btn" href="<?= htmlspecialchars($basePath) ?>/recycler/e-lot/<?= rawurlencode($lot['code']) ?>">View Details</a><?php if ($lot['bid']==='SUBMITTED'): ?><button class="edit-btn" type="button" data-recycler-dialog="view-bid" data-elot-code="<?= htmlspecialchars($lot['code']) ?>" data-bid-amount="<?= $lot['amount'] ?>" data-bid-status="Submitted" data-deadline="<?= htmlspecialchars($lot['deadline']) ?>">View Bid</button><?php else: ?><button class="edit-btn" type="button" data-recycler-dialog="place-bid" data-elot-code="<?= htmlspecialchars($lot['code']) ?>">Place Bid</button><?php endif; ?></div></td>
 </tr><?php endforeach; ?></tbody></table></div><div class="filtered-empty-state" data-eligible-empty hidden>No E-Lots match the selected filters.</div>
</section></section>
